---
# ssh_create_key_home fact is created on role ssh-create-key
- name: Read master host user's id_rsa.pub
  command: cat {{ ssh_create_key_home }}/.ssh/id_rsa.pub
  register: register_ssh_distribute_master_host_id_rsa_pub
  changed_when: False
  when: inventory_hostname == ssh_distribute_master_host

- name: Set id_rsa_pub
  set_fact:
    ssh_distribute_master_host_id_rsa_pub: '{{ register_ssh_distribute_master_host_id_rsa_pub.stdout }}'
  when: inventory_hostname == ssh_distribute_master_host

- name: Add id_rsa.pub to authorized_key
  authorized_key:
    user: '{{ ssh_distribute_slave_host_user }}'
    key: "{{ hostvars[ssh_distribute_master_host]['ssh_distribute_master_host_id_rsa_pub'] }}"

- name: Ensure ssh keys are in known_hosts
  shell: ssh-keyscan {{ inventory_hostname }} {{ ansible_hostname }} >> {{ hostvars[ssh_distribute_master_host]['ssh_create_key_home'] }}/.ssh/known_hosts
  changed_when: False
  delegate_to: '{{ ssh_distribute_master_host }}'
  when: ssh_distribute_add_known_hosts

- name: Ensure ssh keys are in known hosts
  known_hosts:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ inventory_hostname }}'
    - '{{ ansible_hostname }}'
  when: ssh_distribute_add_known_hosts
